# Generated by Django 5.1.6 on 2025-03-06 00:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portafolioBackend', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('slug', models.SlugField(blank=True, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Categorias',
            },
        ),
        migrations.AlterModelOptions(
            name='contacto',
            options={'ordering': ['fecha'], 'verbose_name_plural': 'Mensajes de contacto'},
        ),
        migrations.AlterModelOptions(
            name='proyecto',
            options={'ordering': ['-fecha_creacion'], 'verbose_name_plural': 'Proyectos'},
        ),
        migrations.RemoveField(
            model_name='proyecto',
            name='url_github',
        ),
        migrations.RemoveField(
            model_name='proyecto',
            name='url_proyecto',
        ),
        migrations.AddField(
            model_name='contacto',
            name='respondido',
            field=models.GenericIPAddressField(blank=True, help_text='Ip del usuario', null=True),
        ),
        migrations.AddField(
            model_name='proyecto',
            name='activo',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='proyecto',
            name='demo_url',
            field=models.URLField(blank=True, help_text='Enlace a la demo', verbose_name='URL de Dema'),
        ),
        migrations.AddField(
            model_name='proyecto',
            name='repo_url',
            field=models.URLField(blank=True, help_text='Enlace al repositorio', verbose_name='URL de repositorio'),
        ),
        migrations.AddField(
            model_name='proyecto',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
        migrations.AlterField(
            model_name='proyecto',
            name='tecnologias',
            field=models.JSONField(default=list, help_text='Lista de tecnologías usadas'),
        ),
        migrations.AddField(
            model_name='proyecto',
            name='categoria',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='proyectos', to='portafolioBackend.categoria'),
        ),
    ]
