# Generated by Django 5.1.6 on 2025-03-14 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portafolioBackend', '0002_categoria_alter_contacto_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contacto',
            name='ip',
            field=models.GenericIPAddressField(blank=True, help_text='IP del usuario', null=True),
        ),
        migrations.AlterField(
            model_name='contacto',
            name='respondido',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='proyecto',
            name='demo_url',
            field=models.URLField(blank=True, help_text='Enlace a la demo', verbose_name='URL de Demo'),
        ),
    ]
